import type { Metadata } from 'next'
import { plusJakartaSans, poppins, overpass } from './fonts/fonts'
import './globals.css'
import Navbar from '@/app/components/Navbar'
import Footer from '@/app/components/Footer'

export const metadata: Metadata = {
  title: 'Payboost',
  description: 'Generated by Keila Tech',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${plusJakartaSans.variable} 
          ${poppins.variable} 
          ${overpass.variable} 
          antialiased
        `}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
