import Footer from '@/app/components/footer/Footer'
import Navbar from '@/app/components/navbar/Navbar'
import type { Metadata } from 'next'
import {
  lora,
  montserrat,
  overpass,
  plusJakartaSans,
  poppins,
  syne,
} from './fonts/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Payboost',
  description: 'Generated by Keila Tech',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${plusJakartaSans.variable} 
          ${poppins.variable} 
          ${overpass.variable} 
          ${lora.variable}
          ${montserrat.variable}
          ${syne.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
